### ISSUE TITLE
不支持OS X吗？

### ISSUE THREAD

**Issue by young40** [muzuiget/mare-runner#1]
谢谢

**Comment by muzuiget** [comment]
理论上是支持的，但是 C 模块因为不能在 Linux 服务器交叉编译，还有很多东西等着做，所以先不搞了。你可以按照 http://mare.ejoy.com/post/build-c-module.html 这里「开发」一节的文档编译一下。

**Comment by young40** [comment]
感谢 @muzuiget

**Comment by muzuiget** [comment]
MacOSX 已有打包编译版了。
