### ISSUE TITLE
Error :  v0.2.1 on mac 

### ISSUE THREAD

**Issue by focuskernel** [muzuiget/mare-runner#3]
ttcdeMacBook-Air:mac_x64 ttc$ cd example/
ttcdeMacBook-Air:example ttc$ ./lua -i test.lua 
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
./lua: ./mare/debugvm/debugger.lua:4: module 'mare/debugvm/rdaux' not found:
	no field package.preload['mare/debugvm/rdaux']
	no file '/Users/ttc/.luarocks/share/lua/5.1/mare/debugvm/rdaux.lua'
	no file '/Users/ttc/.luarocks/share/lua/5.1/mare/debugvm/rdaux/init.lua'
	no file '/Users/ttc/torch/install/share/lua/5.1/mare/debugvm/rdaux.lua'
	no file '/Users/ttc/torch/install/share/lua/5.1/mare/debugvm/rdaux/init.lua'
	no file './mare/debugvm/rdaux.lua'
	no file '/Users/ttc/torch/install/share/luajit-2.1.0-beta1/mare/debugvm/rdaux.lua'
	no file '/usr/local/share/lua/5.1/mare/debugvm/rdaux.lua'
	no file '/usr/local/share/lua/5.1/mare/debugvm/rdaux/init.lua'
	no file '/Users/ttc/torch/install/lib/mare/debugvm/rdaux.dylib'
	no file '/Users/ttc/.luarocks/lib/lua/5.1/mare/debugvm/rdaux.so'
	no file '/Users/ttc/torch/install/lib/lua/5.1/mare/debugvm/rdaux.so'
	no file './mare/debugvm/rdaux.so'
	no file '/usr/local/lib/lua/5.1/mare/debugvm/rdaux.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'remotedebug.start'
	test.lua:1: in main chunk
	[C]: in ?
ttcdeMacBook-Air:example ttc$

**Comment by muzuiget** [comment]
云风那个 C 库只支持 Lua 5.3，我看你用 torch，可以用 Lua 5.3 来跑。

**Comment by muzuiget** [comment]
啊，不对，看错，是不是改过环境变量的 `LUA_PATH` ？

**Comment by muzuiget** [comment]
问题解决了吗？什么原因？
